### PR TITLE
LAB_CONDITIONALS with the bonus.

### PR DESCRIPTION
**Pull request by SalemHu**

### CODE REVIEW

**Comment by SalemHu** [comment]
I updated the height formula so it should give an accurate BMI number.

**Comment by wijdan-alharbi** [comment]
You did great on the main question.
For the bonus, **test your code** and make the needed fixes.

**Comment by SalemHu** [comment]
I found a problem in the if statement  will fix it and send it. thank you

**Comment by wijdan-alharbi** [comment]
Well done ✅ .

**Pull request closed without merging**
